global:
  slack_api_url: "https://hooks.slack.com/services/XXXXXXX"
  # The smarthost and SMTP sender used for mail notifications.
#  smtp_smarthost: 'localhost:25'
#  smtp_from: 'alertmanager@example.org'
#  smtp_auth_username: 'alertmanager'
#  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack
  routes:

receivers:
#- name: 'team-X-mails'
#  email_configs:
#  - to: 'team-X+alerts@example.org'

- name: 'slack'
  slack_configs:
  - username: 'Alertmanager'
  - api_url: 'https://hooks.slack.com/services/XXXXXXXX'
  - channel: '#alertmanager'
    send_resolved: true
